SECTION TEXT
INPUT OLD_DATA
LOAD OLD_DATA
RONALDO EQU 2
L1:
DIV DOIS
STORE  NEW_DATA
MULT DOIS ;teste

STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA  ,   OLD_DATA
LOAD OLD_DATA
JMPP L1
IF RONALDO
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE